version: '3.8'

services:
  app:
    image: node:22.5.1
    container_name: edu-center
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - valkey
    logging:
      driver: "json-file"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_APP: ${DB_APP}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_DURATION: ${ACCESS_TOKEN_DURATION}
      REFRESH_TOKEN_DURATION: ${REFRESH_TOKEN_DURATION}
      VALKEY_HOST: ${VALKEY_HOST}
      VALKEY_PORT: ${VALKEY_PORT}
    command: >
      sh -c "npm install && npm start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  valkey:
    image: valkey/valkey:8
    container_name: valkey-cache
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: always
    command: redis-server

volumes:
  valkey_data:
    driver: local
