version: '3.8'

services:
  app:
    image: node:22.5.1
    container_name: edu-center
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - valkey
    logging:
      driver: "json-file"
    environment:
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
    env_file:
      - .env
    command: >
      sh -c "npm install && npm start"
    restart: always

  valkey:
    image: valkey/valkey:8
    container_name: valkey-cache
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: always
    command: redis-server

volumes:
  valkey_data:
    driver: local
