const express = require('express')
const userRoutes = require('./user.route')
const studentRoutes = require('./student.route')
const classRoutes = require('./class.route')
const chatRoutes = require('./chat.route')
const courseRoutes = require('./course.route')
const classSessionRoutes = require('./classSession.route')
const uploadRoutes = require('./upload.route')
const teacherRoutes = require('./teacher.route')
const billingRoutes = require('./bill.route')
const assignmentRoutes = require('./assignment.route')
const class_postRoutes = require('./class_post.route')

const router = express.Router()

router.use(userRoutes)
router.use(studentRoutes)
router.use(classRoutes)
router.use(chatRoutes)
router.use(courseRoutes)
router.use(classSessionRoutes)
router.use(uploadRoutes)
router.use(teacherRoutes)
router.use(billingRoutes)
router.use(assignmentRoutes)
router.use(class_postRoutes)

module.exports = router